# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9a75e178db37841820c8d17f73d1e0c1564fe637ce99c6c4339b0e03ae6d51ab1146fcb16787679b20ee3e347a5af2e97f1a6ab0b2d858a1d413b312551055cb

test:
  secret_key_base: 729dbbe9af9d2e9258e9e89d49b2d1fbf3747ec418dfcf72384faa9374dde9767f9c90d40e16faf81fee303004206f7c770f156a4fa76a6d831aa164735f1f4a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
